# Generated by Django 5.0.1 on 2024-03-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
